-- Seed lessons with numbered names.
-- ON CONFLICT DO UPDATE so existing rows get the new numbered name.
INSERT INTO lessons (id, name, new_letters, sort_order) VALUES
  ('vocales', '1. Vocales', ARRAY['a','e','i','o','u'], 1),
  ('ojo',     '2. Ojo',     ARRAY['j'],                 2),
  ('mama',    '3. Mamá',    ARRAY['m'],                 3),
  ('mano',    '4. Mano',    ARRAY['n'],                 4),
  ('lana',    '5. Lana',    ARRAY['l'],                 5),
  ('loro',    '6. Loro',    ARRAY['r'],                 6),
  ('nido',    '7. Nido',    ARRAY['d'],                 7),
  ('pino',    '8. Pino',    ARRAY['p'],                 8),
  ('pato',    '9. Pato',    ARRAY['t'],                 9),
  ('gato',    '10. Gato',   ARRAY['g'],                10)
ON CONFLICT (id) DO UPDATE
  SET name        = EXCLUDED.name,
      new_letters = EXCLUDED.new_letters,
      sort_order  = EXCLUDED.sort_order;

-- Seed words for lessons 2-10.
-- Vocales words already exist (added manually); skip with DO NOTHING.
INSERT INTO words (id, text, type, lesson_id, active) VALUES
  -- 1. Vocales (vocales words already in DB — kept here so a fresh DB also works)
  ('vocales_0',  'a',   'silaba', 'vocales', true),
  ('vocales_1',  'e',   'silaba', 'vocales', true),
  ('vocales_2',  'i',   'silaba', 'vocales', true),
  ('vocales_3',  'o',   'silaba', 'vocales', true),
  ('vocales_4',  'u',   'silaba', 'vocales', true),
  ('vocales_5',  'ae',  'silaba', 'vocales', true),
  ('vocales_6',  'ai',  'silaba', 'vocales', true),
  ('vocales_7',  'ao',  'silaba', 'vocales', true),
  ('vocales_8',  'au',  'silaba', 'vocales', true),
  ('vocales_9',  'ea',  'silaba', 'vocales', true),
  ('vocales_10', 'ei',  'silaba', 'vocales', true),
  ('vocales_11', 'eo',  'silaba', 'vocales', true),
  ('vocales_12', 'eu',  'silaba', 'vocales', true),
  ('vocales_13', 'ia',  'silaba', 'vocales', true),
  ('vocales_14', 'ie',  'silaba', 'vocales', true),
  ('vocales_15', 'io',  'silaba', 'vocales', true),
  ('vocales_16', 'iu',  'silaba', 'vocales', true),
  ('vocales_17', 'oa',  'silaba', 'vocales', true),
  ('vocales_18', 'oe',  'silaba', 'vocales', true),
  ('vocales_19', 'oi',  'silaba', 'vocales', true),
  ('vocales_20', 'ua',  'silaba', 'vocales', true),
  ('vocales_21', 'ue',  'silaba', 'vocales', true),
  ('vocales_22', 'ui',  'silaba', 'vocales', true),
  ('vocales_23', 'uo',  'silaba', 'vocales', true),

  -- 2. Ojo (+J)
  ('ojo_0', 'ají',  'palabra', 'ojo', true),
  ('ojo_1', 'ojo',  'palabra', 'ojo', true),
  ('ojo_2', 'ajo',  'palabra', 'ojo', true),
  ('ojo_3', 'eje',  'palabra', 'ojo', true),

  -- 3. Mamá (+M)
  ('mama_0',  'mamá',           'palabra', 'mama', true),
  ('mama_1',  'mima',           'palabra', 'mama', true),
  ('mama_2',  'memo',           'palabra', 'mama', true),
  ('mama_3',  'mina',           'palabra', 'mama', true),
  ('mama_4',  'amé',            'palabra', 'mama', true),
  ('mama_5',  'amo',            'palabra', 'mama', true),
  ('mama_6',  'mía',            'palabra', 'mama', true),
  ('mama_7',  'miau',           'palabra', 'mama', true),
  ('mama_8',  'mimo',           'palabra', 'mama', true),
  ('mama_9',  'mama',           'palabra', 'mama', true),
  ('mama_10', 'mame',           'palabra', 'mama', true),
  ('mama_11', 'mío',            'palabra', 'mama', true),
  ('mama_12', 'moai',           'palabra', 'mama', true),
  ('mama_13', 'moja',           'palabra', 'mama', true),
  ('mama_14', 'mojo',           'palabra', 'mama', true),
  ('mama_15', 'momia',          'palabra', 'mama', true),
  ('mama_16', 'mi mamá',        'frase',   'mama', true),
  ('mama_17', 'mojo a mi moai', 'frase',   'mama', true),

  -- 4. Mano (+N)
  ('mano_0',  'mono',          'palabra', 'mano', true),
  ('mano_1',  'mina',          'palabra', 'mano', true),
  ('mano_2',  'maní',          'palabra', 'mano', true),
  ('mano_3',  'enano',         'palabra', 'mano', true),
  ('mano_4',  'ajeno',         'palabra', 'mano', true),
  ('mano_5',  'manojo',        'palabra', 'mano', true),
  ('mano_6',  'enojo',         'palabra', 'mano', true),
  ('mano_7',  'jamón',         'palabra', 'mano', true),
  ('mano_8',  'monja',         'palabra', 'mano', true),
  ('mano_9',  'enojón',        'palabra', 'mano', true),
  ('mano_10', 'mi mano',       'frase',   'mano', true),
  ('mano_11', 'una monja',     'frase',   'mano', true),
  ('mano_12', 'un mono enano', 'frase',   'mano', true),

  -- 5. Lana (+L)
  ('lana_0', 'lila',  'palabra', 'lana', true),
  ('lana_1', 'luna',  'palabra', 'lana', true),
  ('lana_2', 'lija',  'palabra', 'lana', true),
  ('lana_3', 'jalea', 'palabra', 'lana', true),
  ('lana_4', 'mula',  'palabra', 'lana', true),
  ('lana_5', 'ola',   'palabra', 'lana', true),
  ('lana_6', 'milo',  'palabra', 'lana', true),

  -- 6. Loro (+R)
  ('loro_0',  'aro',                    'palabra', 'loro', true),
  ('loro_1',  'marino',                 'palabra', 'loro', true),
  ('loro_2',  'mora',                   'palabra', 'loro', true),
  ('loro_3',  'lirio',                  'palabra', 'loro', true),
  ('loro_4',  'naranja',                'palabra', 'loro', true),
  ('loro_5',  'número',                 'palabra', 'loro', true),
  ('loro_6',  'oreja',                  'palabra', 'loro', true),
  ('loro_7',  'memoria',                'palabra', 'loro', true),
  ('loro_8',  'jurel',                  'palabra', 'loro', true),
  ('loro_9',  'mamá mira mi muela',     'frase',   'loro', true),
  ('loro_10', 'el minero mira la mina', 'frase',   'loro', true),
  ('loro_11', 'el aro en la oreja',     'frase',   'loro', true),

  -- 7. Nido (+D)
  ('nido_0',  'dedal',                                   'palabra', 'nido', true),
  ('nido_1',  'día',                                     'palabra', 'nido', true),
  ('nido_2',  'dilema',                                  'palabra', 'nido', true),
  ('nido_3',  'dominó',                                  'palabra', 'nido', true),
  ('nido_4',  'mudo',                                    'palabra', 'nido', true),
  ('nido_5',  'mundial',                                 'palabra', 'nido', true),
  ('nido_6',  'nada',                                    'palabra', 'nido', true),
  ('nido_7',  'marido',                                  'palabra', 'nido', true),
  ('nido_8',  'duende',                                  'palabra', 'nido', true),
  ('nido_9',  'la marejada dejó un jurel en la arena',   'frase',   'nido', true),
  ('nido_10', 'al duende le duele el oído',              'frase',   'nido', true),

  -- 8. Pino (+P)
  ('pino_0',  'apuro',                              'palabra', 'pino', true),
  ('pino_1',  'papel',                              'palabra', 'pino', true),
  ('pino_2',  'pipa',                               'palabra', 'pino', true),
  ('pino_3',  'pulmón',                             'palabra', 'pino', true),
  ('pino_4',  'pala',                               'palabra', 'pino', true),
  ('pino_5',  'pepino',                             'palabra', 'pino', true),
  ('pino_6',  'paloma',                             'palabra', 'pino', true),
  ('pino_7',  'pino',                               'palabra', 'pino', true),
  ('pino_8',  'pera',                               'palabra', 'pino', true),
  ('pino_9',  'pulmonía',                           'palabra', 'pino', true),
  ('pino_10', 'peral',                              'palabra', 'pino', true),
  ('pino_11', 'emparedado',                         'palabra', 'pino', true),
  ('pino_12', 'el puma empuja al pudú',             'frase',   'pino', true),
  ('pino_13', 'me da pena el pájaro en la pajarera','frase',   'pino', true),

  -- 9. Pato (+T)
  ('pato_0',  'temario',                                              'palabra', 'pato', true),
  ('pato_1',  'tela',                                                 'palabra', 'pato', true),
  ('pato_2',  'atuendo',                                              'palabra', 'pato', true),
  ('pato_3',  'jote',                                                 'palabra', 'pato', true),
  ('pato_4',  'lata',                                                 'palabra', 'pato', true),
  ('pato_5',  'mate',                                                 'palabra', 'pato', true),
  ('pato_6',  'lenteja',                                              'palabra', 'pato', true),
  ('pato_7',  'puente',                                               'palabra', 'pato', true),
  ('pato_8',  'diente',                                               'palabra', 'pato', true),
  ('pato_9',  'pelota',                                               'palabra', 'pato', true),
  ('pato_10', 'tina',                                                 'palabra', 'pato', true),
  ('pato_11', 'tomate',                                               'palabra', 'pato', true),
  ('pato_12', 'patín',                                                'palabra', 'pato', true),
  ('pato_13', 'en la maleta meten la paleta, la pelota y la pala',    'frase',   'pato', true),
  ('pato_14', 'la marioneta anda en patineta en el patio',            'frase',   'pato', true),

  -- 10. Gato (+G)
  ('gato_0',  'agua',                                  'palabra', 'gato', true),
  ('gato_1',  'golpe',                                 'palabra', 'gato', true),
  ('gato_2',  'pegamento',                             'palabra', 'gato', true),
  ('gato_3',  'goma',                                  'palabra', 'gato', true),
  ('gato_4',  'nogal',                                 'palabra', 'gato', true),
  ('gato_5',  'mango',                                 'palabra', 'gato', true),
  ('gato_6',  'lenguaje',                              'palabra', 'gato', true),
  ('gato_7',  'elegante',                              'palabra', 'gato', true),
  ('gato_8',  'garantía',                              'palabra', 'gato', true),
  ('gato_9',  'laguna',                                'palabra', 'gato', true),
  ('gato_10', 'galope',                                'palabra', 'gato', true),
  ('gato_11', 'el orangután mira el nogal',            'frase',   'gato', true),
  ('gato_12', 'la iguana tomó la última gota de agua', 'frase',   'gato', true)
ON CONFLICT (id) DO NOTHING;
