CREATE TABLE IF NOT EXISTS words (
  id      TEXT PRIMARY KEY,
  text    TEXT NOT NULL,
  type    TEXT NOT NULL DEFAULT 'palabra',
  level   INTEGER NOT NULL DEFAULT 1,
  active  BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE words ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public access" ON words FOR ALL USING (true) WITH CHECK (true);